[build]
# Only build the websocket-server directory
rootDirectory = "websocket-server"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
interval = 30